# Fill in this file with the Dockerfile instructions as described in the README.md

# NOTE: When filling in this file, assume this file is located inside the
# toyota-data-feeder directory like following:

#        toyota-data-feeder/
#        ├── Dockerfile
#        ├── ca.crt
#        ├── feeder.py
#        ├── readme.md
#        ├── requirements.txt
#        ├── toyota_data.csv
#        └── assets